title: Olanrewaju Oyenekan
logo: Data_Analytics_2023.jpg
description: A data analyst with 5 years of experience in the use of advanced excel for reporting, SQL for query and PowerBi for visualizing insights
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
